### ISSUE TITLE
Red trust proved ?

### ISSUE THREAD

**Issue by masterlinnn** [Liuhaixv/csgo-hitsound-maker-external#5]
Hey, i tested this application, it works  perfect, however it is unknow if it will cause the account to be red trust factor, please advise.

And how can i contact you for technical exchange.

**Comment by FrozenFish259** [comment]
If VAC flags programs that you used when playing game as cheat program, you may get banned in couple of weeks or get permanent red trust.
It's recommended to use [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader) to bypass anti-cheat scan and drastically reduce the likelihood of a VAC ban.It may help reducing red trust possibility.

**Comment by FrozenFish259** [comment]
wechat:yobanihcc

**Comment by masterlinnn** [comment]
Thank you for replying
